apiVersion: v1
kind: Pod
metadata:
  name: init-container-demo
spec:
  initContainers:
  - name: init-container
    image:  busybox
    command:  ['sh','-c','echo Hello > /data/message.txt']
    volumeMounts:
    - name: shared-data
      mountPath:  /data
  containers:
  - name: main-container
    image:  nginx
    volumeMounts:
    - name: shared-data
      mountPath:  /data
  volumes:
  - name: shared-data
    emptyDir: {}
