apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app:  nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  nginx  # This is the name of the label
  template:
    metadata:
      labels:
        app:  nginx # Both name are same as the the matchLabels
    spec:
      nodeSelector: # label the node
        env:  test # On node1 = env [kubectl label node kind-worker env=test]
      containers:
      - name: nginx
        image:  nginx
        ports:
        - containerPort:  80
